export let regions = {
	'Вінницька область': 'Vinnytsia region',
	'Житомирська область': 'Zhytomyr region',
	'Черкаська область': 'Cherkasy region',
	'Миколаївська область': 'Mykolaiv region',
	'Кіровоградська область': 'Kirovohrad region',
	'Хмельницька область': 'Khmelnytsykyi region',
	'Київська область': 'Kyiv region',
	'Івано-Франківська область': 'Ivano-Frankivsk region',
	'Львівська область': 'Lviv region',
	'Рівненська область': 'Rivne region',
	'Волинська область': 'Volyn region',
	'м. Київ': 'Kyiv city',
	'Тернопільська область': 'Ternopil region',
	'Чернігівська область': 'Chernihiv region',
	'Полтавська область': 'Poltava region',
	'Донецька область': 'Donetsk region',
	'Сумська область': 'Sumy region',
	'Дніпропетровська область': 'Dnipro region',
	'Харківська область': 'Kharkiv region',
	'Одеська область': 'Odesa region',
	'Запорізька область': 'Zaporizhzhia region',
	'Чернівецька область': 'Chernivtsi region',
	'Закарпатська область': 'Zakarpattia region',
	'Луганська область': 'Luhansk region',
	'Херсонська область': 'Cherson region'
};
